name: Speedaf Login Bot

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install puppeteer tesseract.js form-data

      - name: Run Login Script
        env:
          SPEEDAF_USER: ${{ secrets.SPEEDAF_USER }}
          SPEEDAF_PASS: ${{ secrets.SPEEDAF_PASS }}
          # ربطنا المتغيرات الجديدة هنا
          TELEGRAM_TOKEN_SPEEDAF: ${{ secrets.TELEGRAM_TOKEN_SPEEDAF }}
          TELEGRAM_CHAT_ID_SPEEDAF: ${{ secrets.TELEGRAM_CHAT_ID_SPEEDAF }}
        run: node login.js
