name: Speedaf Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      SPEEDAF_USER: ${{ secrets.SPEEDAF_USER }}
      SPEEDAF_PASS: ${{ secrets.SPEEDAF_PASS }}
      TELEGRAM_CHAT_ID_SPEEDAF: ${{ secrets.TELEGRAM_CHAT_ID_SPEEDAF }}
      TELEGRAM_TOKEN_SPEEDAF: ${{ secrets.TELEGRAM_TOKEN_SPEEDAF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run script
        run: node speedaf.js
